(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&d(a)}).observe(document,{childList:!0,subtree:!0});function c(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function d(t){if(t.ep)return;t.ep=!0;const o=c(t);fetch(t.href,o)}})();document.addEventListener("DOMContentLoaded",()=>{const l=document.querySelector(".menu-button"),n=l.querySelector(".icon"),c=document.querySelector(".modal"),d=document.querySelectorAll(".menu-list-item"),t=document.querySelector(".header");let o=!1;const a=`
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect x="0.5" y="0.5" width="23" height="23" rx="3.5" stroke="#a855f7" />
        
        <path d="M5.625 7.125H18.375M5.625 16.125H18.375M5.625 11.625H18.375" 
              stroke="#f5f3ff"
              stroke-linecap="round" />
    </svg>

    `,i=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect x="0.5" y="0.5" width="23" height="23" rx="3.5" stroke="#a855f7" />
  
  <path d="M5.25 5.25L12 12M12 12L5.25 18.75M12 12L18.75 18.75M12 12L18.75 5.25" 
        stroke="#f5f3ff" 
        stroke-linecap="round" 
        stroke-linejoin="round" />
</svg>
    `;l.addEventListener("click",()=>{o=!o,n.innerHTML=o?i:a,o?e():r()}),d.forEach(u=>u.addEventListener("click",()=>{r(),n.innerHTML=a,o=!1})),window.addEventListener("scroll",s);function e(){c.style.display="block"}function r(){c.style.display="none"}function s(){t&&(window.scrollY>60?t.classList.add("header-scroll"):t.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function l(){const i=document.getElementById("site-header");return i?i.offsetHeight:0}function n(i){const e=document.getElementById(i);if(!e)return;const r=l(),s=e.getBoundingClientRect().top+window.pageYOffset-r;window.scrollTo({top:s,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(i=>{i.addEventListener("click",function(e){const r=this.getAttribute("href");if(!r)return;const[s,u]=r.split("#");if(!u)return;const h=window.location.pathname.split("/").pop();!(s===""||s==="./"||s===h||s==="./"+h)||!document.getElementById(u)||(e.preventDefault(),n(u),o(u))})});const d=document.querySelectorAll("section[id]"),t=document.querySelectorAll(".navigation-item");function o(i){t.forEach(r=>r.classList.remove("active"));const e=document.querySelector(`.navigation-item a[href*="#${i}"]`);e&&e.closest(".navigation-item").classList.add("active")}function a(){const i=window.pageYOffset+l()+100;d.forEach(e=>{const r=e.offsetTop,s=r+e.offsetHeight;i>=r&&i<s&&o(e.id)})}if(window.addEventListener("scroll",a),window.location.hash){const i=window.location.hash.substring(1);setTimeout(()=>{n(i),o(i)},300)}});window.addEventListener("load",()=>{const l=document.querySelector(".cursor-glow");window.addEventListener("mousemove",e=>{gsap.to(l,{x:e.clientX,y:e.clientY,duration:1,ease:"power2.out"});const r=(e.clientX-window.innerWidth/2)*.02,s=(e.clientY-window.innerHeight/2)*.02;gsap.to(".hero-content",{x:r,y:s,duration:1,ease:"power2.out"}),gsap.to(".t-left",{x:-r*2,y:-s*2,duration:1.5}),gsap.to(".b-right",{x:r*2,y:s*2,duration:1.5})});const n=document.getElementById("particleCanvas"),c=n.getContext("2d");function d(){n.width=window.innerWidth,n.height=window.innerHeight}d(),window.addEventListener("resize",d);let t=[];const o=100;class a{constructor(){this.reset()}reset(){this.x=Math.random()*n.width,this.y=Math.random()*n.height,this.size=Math.random()*2+.5,this.speedX=Math.random()*.5-.25,this.speedY=Math.random()*.5-.25,this.opacity=Math.random()*.6}update(){this.x+=this.speedX,this.y+=this.speedY,(this.x<0||this.x>n.width||this.y<0||this.y>n.height)&&this.reset()}draw(){c.fillStyle=`rgba(168, 85, 247, ${this.opacity})`,c.beginPath(),c.arc(this.x,this.y,this.size,0,Math.PI*2),c.fill()}}for(let e=0;e<o;e++)t.push(new a);function i(){c.clearRect(0,0,n.width,n.height),t.forEach(e=>{e.update(),e.draw()}),requestAnimationFrame(i)}i()});
//# sourceMappingURL=index.js.map
