(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&d(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function d(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();document.addEventListener("DOMContentLoaded",()=>{const l=document.querySelector(".menu-button"),n=l.querySelector(".icon"),s=document.querySelector(".modal"),d=document.querySelectorAll(".menu-list-item"),t=document.querySelector(".header");let o=!1;const c=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect x="0.5" y="0.5" width="23" height="23" rx="3.5" stroke="#FFC401" />
  <path d="M5.625 7.125H18.375M5.625 16.125H18.375M5.625 11.625H18.375" stroke="#F1EEE1" stroke-linecap="round" />
</svg>
    `,e=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect x="0.5" y="0.5" width="23" height="23" rx="3.5" stroke="#FFC401" />
  <path d="M5.25 5.25L12 12M12 12L5.25 18.75M12 12L18.75 18.75M12 12L18.75 5.25" stroke="#F1EEE1" stroke-linecap="round" stroke-linejoin="round" />
</svg>
    `;l.addEventListener("click",()=>{o=!o,n.innerHTML=o?e:c,o?i():r()}),d.forEach(h=>h.addEventListener("click",()=>{r(),n.innerHTML=c,o=!1})),window.addEventListener("scroll",a);function i(){s.style.display="block"}function r(){s.style.display="none"}function a(){t&&(window.scrollY>60?t.classList.add("header-scroll"):t.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function l(){const e=document.getElementById("site-header");return e?e.offsetHeight:0}function n(e){const i=document.getElementById(e);if(!i)return;const r=l(),a=i.getBoundingClientRect().top+window.pageYOffset-r;window.scrollTo({top:a,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(e=>{e.addEventListener("click",function(i){const r=this.getAttribute("href");if(!r)return;const[a,h]=r.split("#");if(!h)return;const u=window.location.pathname.split("/").pop();!(a===""||a==="./"||a===u||a==="./"+u)||!document.getElementById(h)||(i.preventDefault(),n(h),o(h))})});const d=document.querySelectorAll("section[id]"),t=document.querySelectorAll(".navigation-item");function o(e){t.forEach(r=>r.classList.remove("active"));const i=document.querySelector(`.navigation-item a[href*="#${e}"]`);i&&i.closest(".navigation-item").classList.add("active")}function c(){const e=window.pageYOffset+l()+100;d.forEach(i=>{const r=i.offsetTop,a=r+i.offsetHeight;e>=r&&e<a&&o(i.id)})}if(window.addEventListener("scroll",c),window.location.hash){const e=window.location.hash.substring(1);setTimeout(()=>{n(e),o(e)},300)}});window.addEventListener("load",()=>{const l=document.querySelector(".cursor-glow");window.addEventListener("mousemove",e=>{gsap.to(l,{x:e.clientX,y:e.clientY,duration:1,ease:"power2.out"});const i=(e.clientX-window.innerWidth/2)*.02,r=(e.clientY-window.innerHeight/2)*.02;gsap.to(".hero-content",{x:i,y:r,duration:1,ease:"power2.out"})});const n=document.getElementById("particleCanvas"),s=n.getContext("2d");n.width=window.innerWidth,n.height=window.innerHeight;let d=[];const t=80;class o{constructor(){this.reset()}reset(){this.x=Math.random()*n.width,this.y=Math.random()*n.height,this.size=Math.random()*2+.5,this.speedX=Math.random()*.5-.25,this.speedY=Math.random()*.5-.25,this.opacity=Math.random()*.5}update(){this.x+=this.speedX,this.y+=this.speedY,(this.x<0||this.x>n.width||this.y<0||this.y>n.height)&&this.reset()}draw(){s.fillStyle=`rgba(181, 134, 13, ${this.opacity})`,s.beginPath(),s.arc(this.x,this.y,this.size,0,Math.PI*2),s.fill()}}for(let e=0;e<t;e++)d.push(new o);function c(){s.clearRect(0,0,n.width,n.height),d.forEach(e=>{e.update(),e.draw()}),requestAnimationFrame(c)}c()});
//# sourceMappingURL=index.js.map
